### ISSUE TITLE
download_phenocam should document that sitename is a regular expression.

### ISSUE THREAD

**Issue by tmilliman** [khufkens/phenocamr#10]
The example `download_phenocam()` command grabs multiple sites which match the string 'harvard'.  The help for this function should note that the site argument is a regular expression.   And perhaps the example should use 'harvard$' as the site name.

**Comment by khufkens** [comment]
fixed, brief mention in docs provided https://github.com/khufkens/phenocamr/commit/ee31df312adb2e312e4ee96f85ba9df575d354dd
