### ISSUE TITLE
download_phenocam() with frequency = 1 is inconsistent with frequency = 3.

### ISSUE THREAD

**Issue by tmilliman** [khufkens/phenocamr#11]
Not sure how this is supposed to work but when I use frequency=1 I get the following error message:

```
    > download_phenocam(site = "harvard$",
    +                   veg_type = "DB",
    +                   roi_id = "1000",
    +                   frequency = "1",
    +                   contract=FALSE)
    Downloading: harvard_DB_1000_1day.csv
    Error in contract_phenocam(data, internal = TRUE, no_padding = TRUE) : 
      This is a 1-day file, will not be contracted to 3-day frequency

```
And the resulting downloaded file is not padded with the +/- 90 days.   My expectations were that the download would result in a file with padding as was the case with the 3-day frequency.  This seems to be a problem with `expand_phenocam()` calling `contract_phenocam()` which fails for the 1-day file and stops the padding from occurring.  I've got a local workaround but not sure if the logic matches your intent.

**Comment by khufkens** [comment]
Copy paste of an general error trap which didn't apply... just released 1.1.1 with this bug... damn. For some reason I don't get emails when issues are filed. Fixed as per below, will be in release 1.1.2 next week, grab the dev version for now.

https://github.com/khufkens/phenocamr/commit/396510150958dae1ce17e50be0c80c62d9b507fb
