### ISSUE TITLE
Documentation example error

### ISSUE THREAD

**Issue by tmilliman** [khufkens/phenocamr#9]
Example usage should be:

download_phenocam(site = "harvard",
                  vegetation = "DB",
                  frequency = 3,
                  phenophase = TRUE)

i.e. argument is 'phenophase' not 'phenophases'.

**Comment by khufkens** [comment]
slowly fixing docs + added code coverage and unit testing to all R packages https://github.com/khufkens/phenocamr/commit/1d35058f333924f15118e31c155d603d6824bfcd
